from __future__ import annotations

from typing import Any


PROVIDER_PRESETS: list[dict[str, Any]] = [
    {
        "provider_type": "mock",
        "label": "Mock / Local Validation",
        "litellm_provider": "mock",
        "default_base_url": "mock://local",
        "use_default_base_url_when_blank": False,
        "default_model": "mock-model",
        "protocol": "local",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Local mock mode. Usually only name and model matter; no external API call is made.",
        "notes": "No external network call. Useful for local verification.",
    },
    {
        "provider_type": "openai",
        "label": "OpenAI",
        "litellm_provider": "openai",
        "default_base_url": "https://api.openai.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "gpt-4.1-mini",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": True,
        "show_advanced_by_default": False,
        "quickstart_hint": "Usually only API Key and model are needed. Keep the default OpenAI endpoint unless you use a proxy.",
        "notes": "LiteLLM routes this through the OpenAI chat API.",
    },
    {
        "provider_type": "deepseek",
        "label": "DeepSeek",
        "litellm_provider": "deepseek",
        "default_base_url": "https://api.deepseek.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "deepseek-chat",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Usually only API Key and model are needed. Keep the default DeepSeek endpoint unless you use a proxy.",
        "notes": "DeepSeek chat is handled by LiteLLM.",
    },
    {
        "provider_type": "openrouter",
        "label": "OpenRouter",
        "litellm_provider": "openrouter",
        "default_base_url": "https://openrouter.ai/api/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "openai/gpt-4.1-mini",
        "protocol": "openrouter",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Usually API Key and model are enough. Extra headers are optional if you want app attribution metadata.",
        "notes": "OpenRouter uses its own LiteLLM provider route.",
    },
    {
        "provider_type": "ollama",
        "label": "Ollama",
        "litellm_provider": "ollama",
        "default_base_url": "http://localhost:11434/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "qwen2.5:7b",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Local Ollama usually needs Base URL and model. API Key can stay empty.",
        "notes": "LiteLLM talks to the Ollama OpenAI-compatible endpoint.",
    },
    {
        "provider_type": "custom_openai",
        "label": "Custom OpenAI-Compatible",
        "litellm_provider": "openai",
        "default_base_url": "https://your-endpoint.example.com/v1",
        "use_default_base_url_when_blank": False,
        "default_model": "your-model",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": True,
        "show_advanced_by_default": True,
        "quickstart_hint": "Custom gateways usually need Base URL, model, and sometimes custom headers.",
        "notes": "Use this for self-hosted or gateway endpoints that speak the OpenAI API.",
    },
    {
        "provider_type": "azure_openai",
        "label": "Azure OpenAI",
        "litellm_provider": "azure",
        "default_base_url": "https://your-resource.openai.azure.com",
        "use_default_base_url_when_blank": False,
        "default_model": "your-deployment-name",
        "default_api_version": "2024-10-21",
        "protocol": "azure-openai",
        "supports_api_version": True,
        "supports_organization": False,
        "show_advanced_by_default": True,
        "quickstart_hint": "Azure usually needs Base URL, deployment name as model, API Key, and API Version.",
        "notes": "LiteLLM expects the Azure deployment name as the model value.",
    },
    {
        "provider_type": "anthropic",
        "label": "Anthropic",
        "litellm_provider": "anthropic",
        "default_base_url": "https://api.anthropic.com",
        "use_default_base_url_when_blank": True,
        "default_model": "claude-3-7-sonnet-latest",
        "protocol": "anthropic-messages",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Usually only API Key and model are needed. Use advanced headers only if your tenant needs them.",
        "notes": "Anthropic requests are normalized through LiteLLM.",
    },
    {
        "provider_type": "gemini",
        "label": "Google Gemini",
        "litellm_provider": "gemini",
        "default_base_url": "https://generativelanguage.googleapis.com/v1beta",
        "use_default_base_url_when_blank": True,
        "default_model": "gemini-2.0-flash",
        "protocol": "gemini",
        "supports_api_version": False,
        "supports_organization": False,
        "show_advanced_by_default": False,
        "quickstart_hint": "Usually only API Key and model are needed. Keep the default Google AI Studio endpoint unless you proxy it.",
        "notes": "Gemini is routed through LiteLLM's gemini provider path.",
    },
]


def list_provider_presets() -> list[dict[str, Any]]:
    return [dict(item) for item in PROVIDER_PRESETS]


def preset_for(provider_type: str) -> dict[str, Any]:
    for item in PROVIDER_PRESETS:
        if item["provider_type"] == provider_type:
            return dict(item)
    raise KeyError(f"Unknown provider type `{provider_type}`.")
