from __future__ import annotations

from typing import Any


PROVIDER_PRESETS: list[dict[str, Any]] = [
    {
        "provider_type": "openai",
        "label": "OpenAI Official API",
        "litellm_provider": "openai",
        "default_base_url": "https://api.openai.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "gpt-4.1-mini",
        "protocol": "openai",
        "supports_api_version": False,
        "supports_organization": True,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "discovery_mode": "openai",
        "quickstart_hint": "Use for the official OpenAI API. Usually only API Key and Base URL are needed.",
        "notes": "Suitable for chat and embedding models.",
    },
    {
        "provider_type": "custom_openai",
        "label": "OpenAI Compatible API",
        "litellm_provider": "openai",
        "default_base_url": "https://your-endpoint.example.com/v1",
        "use_default_base_url_when_blank": False,
        "default_model": "your-chat-model",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": True,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "discovery_mode": "openai",
        "quickstart_hint": "Use for self-hosted gateways, proxies, or third-party OpenAI-compatible APIs.",
        "notes": "Uses standard OpenAI-compatible endpoints such as /models, /chat/completions, and /embeddings.",
    },
    {
        "provider_type": "azure_openai",
        "label": "Azure OpenAI",
        "litellm_provider": "azure",
        "default_base_url": "https://your-resource.openai.azure.com",
        "use_default_base_url_when_blank": False,
        "default_model": "your-deployment-name",
        "default_api_version": "2024-10-21",
        "protocol": "azure-openai",
        "supports_api_version": True,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "discovery_mode": "azure-openai",
        "quickstart_hint": "Usually needs resource Base URL, deployment name, API Key, and API Version.",
        "notes": "Chat and embedding models usually map to Azure deployment names.",
    },
    {
        "provider_type": "anthropic",
        "label": "Anthropic Messages API",
        "litellm_provider": "anthropic",
        "default_base_url": "https://api.anthropic.com",
        "use_default_base_url_when_blank": True,
        "default_model": "claude-3-7-sonnet-latest",
        "protocol": "anthropic-messages",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat"],
        "discovery_mode": "anthropic",
        "quickstart_hint": "Use for the official Claude API, mainly for chat models.",
        "notes": "The native Anthropic API is centered on the Messages capability.",
    },
    {
        "provider_type": "gemini",
        "label": "Gemini API",
        "litellm_provider": "gemini",
        "default_base_url": "https://generativelanguage.googleapis.com/v1beta",
        "use_default_base_url_when_blank": True,
        "default_model": "gemini-2.0-flash",
        "protocol": "gemini",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "discovery_mode": "gemini",
        "quickstart_hint": "Use for the official Gemini API with generation and embedding support.",
        "notes": "Model discovery can return metadata such as token limits.",
    },
    {
        "provider_type": "cohere",
        "label": "Cohere API",
        "litellm_provider": "cohere",
        "default_base_url": "https://api.cohere.com/v2",
        "use_default_base_url_when_blank": True,
        "default_model": "command-r",
        "protocol": "cohere",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "discovery_mode": "cohere",
        "quickstart_hint": "Use for the official Cohere API to manage chat, embedding, and rerank models.",
        "notes": "Rerank testing uses the Cohere Rerank API.",
    },
    {
        "provider_type": "deepseek",
        "label": "DeepSeek API",
        "litellm_provider": "deepseek",
        "default_base_url": "https://api.deepseek.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "deepseek-chat",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "discovery_mode": "openai",
        "quickstart_hint": "DeepSeek currently works mainly through an OpenAI-compatible API mode.",
        "notes": "Suitable for chat and embedding model management.",
    },
    {
        "provider_type": "openrouter",
        "label": "OpenRouter API",
        "litellm_provider": "openrouter",
        "default_base_url": "https://openrouter.ai/api/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "openai/gpt-4.1-mini",
        "protocol": "openrouter",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat"],
        "discovery_mode": "openai",
        "quickstart_hint": "Use for aggregated routing APIs. Usually only API Key and model name are needed.",
        "notes": "Model discovery uses the /models compatible endpoint.",
    },
    {
        "provider_type": "ollama",
        "label": "Ollama Local API",
        "litellm_provider": "ollama",
        "default_base_url": "http://localhost:11434/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "qwen2.5:7b",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "discovery_mode": "openai",
        "quickstart_hint": "Use for a local Ollama service. API Key is usually not required.",
        "notes": "Calls are made through the OpenAI-compatible interface by default.",
    },
    {
        "provider_type": "mock",
        "label": "Mock / Local Validation",
        "litellm_provider": "mock",
        "default_base_url": "mock://local",
        "use_default_base_url_when_blank": False,
        "default_model": "mock-model",
        "protocol": "local",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": False,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "discovery_mode": "local",
        "quickstart_hint": "Local validation mode that does not make external network calls.",
        "notes": "Useful for demos, tests, and offline validation.",
    },
]


def list_provider_presets() -> list[dict[str, Any]]:
    return [dict(item) for item in PROVIDER_PRESETS]


def preset_for(provider_type: str) -> dict[str, Any]:
    for item in PROVIDER_PRESETS:
        if item["provider_type"] == provider_type:
            return dict(item)
    raise KeyError(f"Unknown provider type `{provider_type}`.")
