from __future__ import annotations

from typing import Any


PROVIDER_PRESETS: list[dict[str, Any]] = [
    {
        "provider_type": "openai",
        "label": "OpenAI 官方接口",
        "litellm_provider": "openai",
        "default_base_url": "https://api.openai.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "gpt-4.1-mini",
        "protocol": "openai",
        "supports_api_version": False,
        "supports_organization": True,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "supports_agent_chat": True,
        "discovery_mode": "openai",
        "quickstart_hint": "适合 OpenAI 官方接口，通常只需要 API Key 和 Base URL。",
        "notes": "可用于聊天模型与嵌入模型。",
    },
    {
        "provider_type": "custom_openai",
        "label": "OpenAI 兼容接口",
        "litellm_provider": "openai",
        "default_base_url": "https://your-endpoint.example.com/v1",
        "use_default_base_url_when_blank": False,
        "default_model": "your-chat-model",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": True,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "supports_agent_chat": True,
        "discovery_mode": "openai",
        "quickstart_hint": "适合自建网关、代理或第三方 OpenAI 兼容接口。",
        "notes": "使用 /models、/chat/completions、/embeddings 等标准 OpenAI 兼容端点。",
    },
    {
        "provider_type": "azure_openai",
        "label": "Azure OpenAI",
        "litellm_provider": "azure",
        "default_base_url": "https://your-resource.openai.azure.com",
        "use_default_base_url_when_blank": False,
        "default_model": "your-deployment-name",
        "default_api_version": "2024-10-21",
        "protocol": "azure-openai",
        "supports_api_version": True,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "supports_agent_chat": True,
        "discovery_mode": "azure-openai",
        "quickstart_hint": "通常需要资源 Base URL、部署名、API Key 和 API Version。",
        "notes": "聊天和嵌入通常走 Azure OpenAI 部署名。",
    },
    {
        "provider_type": "anthropic",
        "label": "Anthropic Messages API",
        "litellm_provider": "anthropic",
        "default_base_url": "https://api.anthropic.com",
        "use_default_base_url_when_blank": True,
        "default_model": "claude-3-7-sonnet-latest",
        "protocol": "anthropic-messages",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat"],
        "supports_agent_chat": True,
        "discovery_mode": "anthropic",
        "quickstart_hint": "适合 Claude 官方接口，主要用于对话模型。",
        "notes": "Anthropic 原生接口当前以 Messages 能力为主。",
    },
    {
        "provider_type": "gemini",
        "label": "Gemini API",
        "litellm_provider": "gemini",
        "default_base_url": "https://generativelanguage.googleapis.com/v1beta",
        "use_default_base_url_when_blank": True,
        "default_model": "gemini-2.0-flash",
        "protocol": "gemini",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "supports_agent_chat": True,
        "discovery_mode": "gemini",
        "quickstart_hint": "适合 Gemini 官方接口，支持生成与嵌入。",
        "notes": "模型获取接口可返回输入 token 上限等元数据。",
    },
    {
        "provider_type": "cohere",
        "label": "Cohere API",
        "litellm_provider": "cohere",
        "default_base_url": "https://api.cohere.com/v2",
        "use_default_base_url_when_blank": True,
        "default_model": "command-r",
        "protocol": "cohere",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "supports_agent_chat": True,
        "discovery_mode": "cohere",
        "quickstart_hint": "适合 Cohere 官方接口，可统一管理聊天、嵌入和重排模型。",
        "notes": "重排测试走 Cohere Rerank API。",
    },
    {
        "provider_type": "deepseek",
        "label": "DeepSeek 接口",
        "litellm_provider": "deepseek",
        "default_base_url": "https://api.deepseek.com/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "deepseek-chat",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "supports_agent_chat": True,
        "discovery_mode": "openai",
        "quickstart_hint": "DeepSeek 当前主要走 OpenAI 兼容模式。",
        "notes": "适合聊天和嵌入类型模型管理。",
    },
    {
        "provider_type": "openrouter",
        "label": "OpenRouter 接口",
        "litellm_provider": "openrouter",
        "default_base_url": "https://openrouter.ai/api/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "openai/gpt-4.1-mini",
        "protocol": "openrouter",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat"],
        "supports_agent_chat": True,
        "discovery_mode": "openai",
        "quickstart_hint": "适合聚合路由类接口，通常只需要 API Key 和模型名。",
        "notes": "模型发现走 /models 兼容接口。",
    },
    {
        "provider_type": "ollama",
        "label": "Ollama 本地接口",
        "litellm_provider": "ollama",
        "default_base_url": "http://localhost:11434/v1",
        "use_default_base_url_when_blank": True,
        "default_model": "qwen2.5:7b",
        "protocol": "openai-compatible",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": True,
        "supported_model_types": ["chat", "embedding"],
        "supports_agent_chat": True,
        "discovery_mode": "openai",
        "quickstart_hint": "适合本地 Ollama 服务，通常不需要 API Key。",
        "notes": "默认按 OpenAI 兼容接口调用。",
    },
    {
        "provider_type": "mock",
        "label": "Mock / 本地验证",
        "litellm_provider": "mock",
        "default_base_url": "mock://local",
        "use_default_base_url_when_blank": False,
        "default_model": "mock-model",
        "protocol": "local",
        "supports_api_version": False,
        "supports_organization": False,
        "supports_model_discovery": False,
        "supported_model_types": ["chat", "embedding", "rerank"],
        "supports_agent_chat": True,
        "discovery_mode": "local",
        "quickstart_hint": "本地验证模式，不发起外部网络调用。",
        "notes": "适合演示、测试和离线验证。",
    },
]


def list_provider_presets() -> list[dict[str, Any]]:
    return [dict(item) for item in PROVIDER_PRESETS]


def preset_for(provider_type: str) -> dict[str, Any]:
    for item in PROVIDER_PRESETS:
        if item["provider_type"] == provider_type:
            return dict(item)
    raise KeyError(f"Unknown provider type `{provider_type}`.")
