ADDITIONAL_COLUMNS: dict[str, dict[str, str]] = {
    "memory_bundles": {
        "bundle_summary": "TEXT",
        "item_count": "INTEGER NOT NULL DEFAULT 0",
        "compression_state": "TEXT",
        "hot_refs": "TEXT",
    },
    "short_term_memories": {
        "bundle_id": "TEXT",
        "text": "TEXT",
        "text_hash": "TEXT",
        "storage_policy": "TEXT NOT NULL DEFAULT 'inline'",
        "storage_ref": "TEXT",
        "payload_bytes": "INTEGER",
        "summary_l0": "TEXT",
        "summary_l1": "TEXT",
        "confidence": "REAL NOT NULL DEFAULT 0.5",
        "visibility": "TEXT NOT NULL DEFAULT 'private_agent'",
        "tier": "TEXT NOT NULL DEFAULT 'working'",
        "version": "INTEGER NOT NULL DEFAULT 1",
        "supersedes_memory_id": "TEXT",
        "superseded_by_memory_id": "TEXT",
        "access_count": "INTEGER NOT NULL DEFAULT 0",
        "last_accessed_at": "TEXT",
        "expires_at": "TEXT",
        "actor_id": "TEXT",
        "participants": "TEXT",
        "compression_state": "TEXT",
    },
    "long_term_memories": {
        "bundle_id": "TEXT",
        "text": "TEXT",
        "text_hash": "TEXT",
        "storage_policy": "TEXT NOT NULL DEFAULT 'inline'",
        "storage_ref": "TEXT",
        "payload_bytes": "INTEGER",
        "summary_l0": "TEXT",
        "summary_l1": "TEXT",
        "confidence": "REAL NOT NULL DEFAULT 0.5",
        "visibility": "TEXT NOT NULL DEFAULT 'private_agent'",
        "tier": "TEXT NOT NULL DEFAULT 'working'",
        "version": "INTEGER NOT NULL DEFAULT 1",
        "supersedes_memory_id": "TEXT",
        "superseded_by_memory_id": "TEXT",
        "access_count": "INTEGER NOT NULL DEFAULT 0",
        "last_accessed_at": "TEXT",
        "expires_at": "TEXT",
        "actor_id": "TEXT",
        "participants": "TEXT",
        "compression_state": "TEXT",
    },
    "memory_events": {
        "session_id": "TEXT",
        "run_id": "TEXT",
        "actor_id": "TEXT",
        "reason_code": "TEXT",
        "source_table": "TEXT",
        "version": "INTEGER",
    },
    "memory_links": {
        "bundle_id": "TEXT",
        "confidence": "REAL NOT NULL DEFAULT 0.5",
        "source_domain": "TEXT",
        "target_domain": "TEXT",
    },
    "archive_memories": {
        "bundle_id": "TEXT",
        "storage_policy": "TEXT NOT NULL DEFAULT 'cold_only'",
        "storage_ref": "TEXT",
        "payload_bytes": "INTEGER",
        "inline_excerpt": "TEXT",
        "summary_l0": "TEXT",
        "summary_l1": "TEXT",
        "visibility": "TEXT",
        "tier": "TEXT",
        "compression_state": "TEXT",
        "source_memory_ids": "TEXT",
        "archive_reason": "TEXT",
    },
    "sessions": {
        "owner_agent_id": "TEXT",
        "interaction_type": "TEXT",
        "subject_type": "TEXT",
        "subject_id": "TEXT",
        "namespace_key": "TEXT",
    },
    "conversation_turns": {
        "speaker_participant_id": "TEXT",
        "target_participant_id": "TEXT",
        "turn_type": "TEXT",
        "salience_score": "REAL",
    },
    "working_memory_snapshots": {
        "owner_agent_id": "TEXT",
        "interaction_type": "TEXT",
        "subject_type": "TEXT",
        "subject_id": "TEXT",
        "constraints": "TEXT",
        "resolved_items": "TEXT",
        "unresolved_items": "TEXT",
        "next_actions": "TEXT",
        "budget_tokens": "INTEGER",
        "salience_vector": "TEXT",
        "compression_revision": "INTEGER NOT NULL DEFAULT 1",
        "namespace_key": "TEXT",
    },
    "runs": {
        "owner_agent_id": "TEXT",
        "interaction_type": "TEXT",
        "subject_type": "TEXT",
        "subject_id": "TEXT",
        "namespace_key": "TEXT",
    },
    "documents": {
        "owner_agent_id": "TEXT",
        "kb_namespace": "TEXT",
        "source_subject_type": "TEXT",
        "source_subject_id": "TEXT",
        "inline_text": "TEXT",
        "inline_excerpt": "TEXT",
        "storage_policy": "TEXT NOT NULL DEFAULT 'large_only'",
        "storage_ref": "TEXT",
        "payload_bytes": "INTEGER",
        "retrieval_count": "INTEGER NOT NULL DEFAULT 0",
        "last_retrieved_at": "TEXT",
        "credibility_score": "REAL NOT NULL DEFAULT 0.5",
        "namespace_key": "TEXT",
    },
    "skills": {
        "owner_agent_id": "TEXT",
        "source_subject_type": "TEXT",
        "source_subject_id": "TEXT",
        "usage_count": "INTEGER NOT NULL DEFAULT 0",
        "last_used_at": "TEXT",
        "success_score": "REAL NOT NULL DEFAULT 0.5",
        "capability_tags": "TEXT",
        "tool_affinity": "TEXT",
        "namespace_key": "TEXT",
        "current_snapshot_id": "TEXT",
    },
    "memory_index": {
        "owner_agent_id": "TEXT",
        "subject_type": "TEXT",
        "subject_id": "TEXT",
        "interaction_type": "TEXT",
        "namespace_key": "TEXT",
        "visibility": "TEXT",
        "tier": "TEXT",
        "access_count": "INTEGER NOT NULL DEFAULT 0",
        "last_accessed_at": "TEXT",
        "actor_id": "TEXT",
    },
    "knowledge_chunk_index": {
        "owner_agent_id": "TEXT",
        "source_subject_type": "TEXT",
        "source_subject_id": "TEXT",
        "namespace_key": "TEXT",
    },
    "skill_index": {
        "owner_agent_id": "TEXT",
        "source_subject_type": "TEXT",
        "source_subject_id": "TEXT",
        "namespace_key": "TEXT",
    },
    "archive_summary_index": {
        "owner_agent_id": "TEXT",
        "subject_type": "TEXT",
        "subject_id": "TEXT",
        "interaction_type": "TEXT",
        "source_type": "TEXT",
        "namespace_key": "TEXT",
    },
    "semantic_index_cache": {
        "source_updated_at": "TEXT",
    },
}

EXTRA_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS memory_bundles (
        id TEXT PRIMARY KEY,
        scope TEXT NOT NULL,
        scope_key TEXT NOT NULL UNIQUE,
        user_id TEXT,
        owner_agent_id TEXT,
        subject_type TEXT,
        subject_id TEXT,
        interaction_type TEXT,
        namespace_key TEXT,
        bundle_summary TEXT,
        item_count INTEGER NOT NULL DEFAULT 0,
        compression_state TEXT,
        hot_refs TEXT,
        metadata TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_memory_bundles_scope ON memory_bundles(scope, owner_agent_id, subject_type, subject_id, interaction_type, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_memory_bundles_namespace ON memory_bundles(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_short_term_memories_bundle ON short_term_memories(bundle_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_long_term_memories_bundle ON long_term_memories(bundle_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_archive_memories_bundle ON archive_memories(bundle_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_short_term_memories_text_hash ON short_term_memories(text_hash, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_long_term_memories_text_hash ON long_term_memories(text_hash, updated_at)",
    """
    CREATE TABLE IF NOT EXISTS participants (
        id TEXT PRIMARY KEY,
        participant_type TEXT NOT NULL,
        external_id TEXT NOT NULL,
        display_name TEXT,
        metadata TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(participant_type, external_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS session_participants (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        participant_id TEXT NOT NULL,
        participant_role TEXT NOT NULL,
        joined_at TEXT NOT NULL,
        metadata TEXT,
        UNIQUE(session_id, participant_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS semantic_index_cache (
        record_id TEXT PRIMARY KEY,
        domain TEXT NOT NULL,
        collection TEXT NOT NULL,
        text TEXT NOT NULL,
        embedding TEXT NOT NULL,
        fingerprint TEXT NOT NULL,
        quality REAL NOT NULL DEFAULT 0.0,
        updated_at TEXT NOT NULL,
        source_updated_at TEXT,
        metadata TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS skill_files (
        id TEXT PRIMARY KEY,
        skill_id TEXT NOT NULL,
        skill_snapshot_id TEXT NOT NULL,
        object_id TEXT NOT NULL,
        relative_path TEXT NOT NULL,
        role TEXT NOT NULL,
        mime_type TEXT,
        size_bytes INTEGER NOT NULL,
        checksum TEXT NOT NULL,
        metadata TEXT,
        created_at TEXT NOT NULL,
        UNIQUE(skill_snapshot_id, relative_path)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS skill_reference_chunks (
        id TEXT PRIMARY KEY,
        skill_id TEXT NOT NULL,
        skill_snapshot_id TEXT NOT NULL,
        file_id TEXT NOT NULL,
        object_id TEXT NOT NULL,
        relative_path TEXT NOT NULL,
        chunk_index INTEGER NOT NULL,
        title TEXT,
        content TEXT NOT NULL,
        metadata TEXT,
        created_at TEXT NOT NULL,
        UNIQUE(file_id, chunk_index)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS skill_reference_index (
        record_id TEXT PRIMARY KEY,
        skill_id TEXT NOT NULL,
        skill_snapshot_id TEXT NOT NULL,
        file_id TEXT NOT NULL,
        object_id TEXT NOT NULL,
        owner_agent_id TEXT,
        source_subject_type TEXT,
        source_subject_id TEXT,
        namespace_key TEXT,
        relative_path TEXT NOT NULL,
        title TEXT,
        text TEXT NOT NULL,
        keywords TEXT,
        updated_at TEXT NOT NULL,
        metadata TEXT
    )
    """,
    """
    CREATE VIRTUAL TABLE IF NOT EXISTS text_search_index USING fts5(
        record_id UNINDEXED,
        domain UNINDEXED,
        collection UNINDEXED,
        title,
        text,
        keywords,
        lexical,
        path,
        updated_at UNINDEXED,
        user_id UNINDEXED,
        owner_agent_id UNINDEXED,
        subject_type UNINDEXED,
        subject_id UNINDEXED,
        interaction_type UNINDEXED,
        session_id UNINDEXED,
        run_id UNINDEXED,
        namespace_key UNINDEXED,
        tokenize = 'unicode61 remove_diacritics 2'
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS handoff_packs (
        id TEXT PRIMARY KEY,
        source_run_id TEXT,
        source_session_id TEXT,
        source_agent_id TEXT,
        target_agent_id TEXT,
        namespace_key TEXT,
        visibility TEXT NOT NULL,
        summary TEXT NOT NULL,
        highlights TEXT,
        open_tasks TEXT,
        constraints TEXT,
        source_refs TEXT,
        metadata TEXT,
        created_at TEXT NOT NULL,
        expires_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reflection_memories (
        id TEXT PRIMARY KEY,
        owner_agent_id TEXT,
        session_id TEXT,
        run_id TEXT,
        reflection_type TEXT NOT NULL,
        summary TEXT NOT NULL,
        details TEXT,
        confidence REAL NOT NULL DEFAULT 0.5,
        decay_half_life_days REAL,
        source_refs TEXT,
        metadata TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS context_artifacts (
        id TEXT PRIMARY KEY,
        artifact_type TEXT NOT NULL,
        session_id TEXT,
        run_id TEXT,
        owner_agent_id TEXT,
        target_agent_id TEXT,
        namespace_key TEXT,
        provider TEXT,
        model TEXT,
        budget_chars INTEGER,
        source_refs TEXT,
        content TEXT NOT NULL,
        metadata TEXT,
        created_at TEXT NOT NULL,
        expires_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS compression_jobs (
        id TEXT PRIMARY KEY,
        job_type TEXT NOT NULL,
        session_id TEXT,
        run_id TEXT,
        owner_agent_id TEXT,
        status TEXT NOT NULL,
        provider TEXT,
        model TEXT,
        request_payload TEXT,
        result_artifact_id TEXT,
        error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS scope_acl_rules (
        id TEXT PRIMARY KEY,
        namespace_key TEXT NOT NULL,
        resource_type TEXT NOT NULL,
        resource_scope TEXT NOT NULL,
        principal_type TEXT NOT NULL,
        principal_id TEXT NOT NULL,
        permission TEXT NOT NULL,
        metadata TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
]

POST_MIGRATION_SCHEMA_STATEMENTS = [
    "CREATE INDEX IF NOT EXISTS idx_participants_lookup ON participants(participant_type, external_id)",
    "CREATE INDEX IF NOT EXISTS idx_session_participants_session ON session_participants(session_id, joined_at)",
    "CREATE INDEX IF NOT EXISTS idx_semantic_index_domain ON semantic_index_cache(domain, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_semantic_index_collection ON semantic_index_cache(collection, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_owner_subject ON sessions(owner_agent_id, subject_type, subject_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_namespace ON sessions(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_turns_speaker ON conversation_turns(session_id, speaker_participant_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_owner ON documents(owner_agent_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_namespace ON documents(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_namespace_storage ON documents(namespace_key, storage_policy, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skills_status ON skills(status, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skills_owner ON skills(owner_agent_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skills_namespace ON skills(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skills_lookup ON skills(name, owner_agent_id, namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skills_current_snapshot ON skills(current_snapshot_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_files_snapshot ON skill_files(skill_snapshot_id, relative_path)",
    "CREATE INDEX IF NOT EXISTS idx_skill_files_skill ON skill_files(skill_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_ref_chunks_snapshot ON skill_reference_chunks(skill_snapshot_id, relative_path, chunk_index)",
    "CREATE INDEX IF NOT EXISTS idx_skill_ref_index_skill ON skill_reference_index(skill_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_ref_index_owner ON skill_reference_index(owner_agent_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_ref_index_namespace ON skill_reference_index(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_memory_index_owner ON memory_index(owner_agent_id, subject_type, subject_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_memory_index_namespace ON memory_index(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_index_owner ON knowledge_chunk_index(owner_agent_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_index_namespace ON knowledge_chunk_index(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_index_owner ON skill_index(owner_agent_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_skill_index_namespace ON skill_index(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_archive_index_owner ON archive_summary_index(owner_agent_id, subject_type, subject_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_archive_index_namespace ON archive_summary_index(namespace_key, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_handoff_packs_route ON handoff_packs(source_agent_id, target_agent_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_reflection_memories_owner_type ON reflection_memories(owner_agent_id, reflection_type, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_context_artifacts_lookup ON context_artifacts(artifact_type, session_id, run_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_compression_jobs_owner_status ON compression_jobs(owner_agent_id, status, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_scope_acl_rules_lookup ON scope_acl_rules(namespace_key, principal_type, principal_id, permission)",
]
